baseURL = "http://blog.0xcc.io/"
languageCode = "ja-JP"
title = "0xcc"
theme = "detox"
PygmentsCodeFences = true
pygmentsstyle = "monokai"
[params]
author = "zchee ( Koichi Shiraishi )"
github = "zchee"
twitter_name = "_zchee_"
useExcerpt = false
