---
version: 2
jobs:
  build:
    docker:
      - image: python:latest  # Use latest stable version
    working_directory: /0xcc.io

    steps:
      - checkout
      - run:
          name: Install pip and Pygments
          command: |
            wget -q -O - https://bootstrap.pypa.io/get-pip.py | python
            pip install Pygments awscli
      - run:
          name: Install hugo and generate public source
          command: |
            wget -q https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_Linux-64bit.deb
            dpkg -i hugo_0.21_Linux-64bit.deb
            hugo
      - deploy:
          name: Upload to GCS
          command: |
            aws s3 sync /0xcc.io/public s3://0xcc.io
